
################################################################################
#
# plot_nmds.R
#
# Here we take in the *.nmds.axes file from the mouse stability analysis and
# plot it in R as we did in Figure 4 of Kozich et al.
#
# Dependencies:   2-D axes file generated by the nmds command in mothur
# Produces:       results/figures/nmds_figure.png
#
################################################################################
library(dplyr)
library(ggplot2)

substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}



axes <- read.table(file="data/mothur/process/sample.final.thetayc.0.03.lt.ave.nmds.axes", 
                   header=T, 
                   row.names=1) %>% 
  mutate(condition = substrRight(rownames(.), 1)) 

ggplot(axes) +
  aes(x=axis1, y=axis2, col=condition) +
  geom_point(pch=19)
